### ISSUE TITLE
运行时可以识别但是点击不起作用

### ISSUE THREAD

**Issue by potoo0** [clouduan/WechatGameAutoPlayer#11]
我安装了依赖，但是运行时可以读出但是无法采取动作，屏幕并没有点击。
cmd输出一致是这个：
get_screenshot: 0.14776s
horizontal_cut: 0.01344s
vertical_cut: 0.00302s
vertical_cut: 0.00398s
recognize: 0.15510s
2+4==6 True
get_screenshot: 0.14250s
horizontal_cut: 0.00330s
vertical_cut: 0.00143s
vertical_cut: 0.00194s
recognize: 0.09820s
2+4==6 True
。您可以给我帮我找找问题吗》？谢谢

**Comment by clouduan** [comment]
```python
                if eval(expr):
                    m.click(loc['click_true_x'], loc['click_true_y'], 1)
                else:
                    m.click(loc['click_false_x'], loc['click_false_y'], 1)
```
这几句出问题了，原因我猜可能是 config.py 里面坐标设置不对，重新设置一下对号和叉号的坐标值

**Comment by potoo0** [comment]
我刚又试了一次还是同样问题。可能是我获取坐标出错，我是这样获取的，win截全图后粘贴到画图板， 画图板的左下角显示的 x, y像素中的x， y。我这样做对吗？

**Comment by potoo0** [comment]
还是我的依赖没有装好？

**Comment by clouduan** [comment]
是的没错。你可以把config文件发来看看，依赖应该没问题

**Comment by potoo0** [comment]
我的config：
location_on_pc = {
'left_top_x': 60,
'left_top_y': 415,
'right_buttom_x': 360,
'right_buttom_y': 605,
'click_true_x': 115,
'click_true_y': 780,
'click_false_x': 295,
'click_false_y': 780
}

**Comment by clouduan** [comment]
看起来你的坐标值设置没问题，这个原因就很迷了，我也不清楚了 :neckbeard: 
你看代码自己调调怎么样？我觉得正常情况应该点击的啊

**Comment by potoo0** [comment]
哦哦， 好的， 谢谢您。
