### ISSUE TITLE
数字和加减符号经常识别错。

### ISSUE THREAD

**Issue by Tangtonton** [clouduan/WechatGameAutoPlayer#14]
我把全部截图保存下来，发现是程序识别图片的时候，有时候会把减号识别成加号。。

**Comment by clouduan** [comment]
那就是程序所用的算法太弱了，_(:з」∠)_这个没办法。

不过我觉得很可能是截图的问题，因为理论上对于这种特别规则的字符图像来说，识别率应该是100%

你可以把分割到的图片 show() 一下看看到底是怎么样的，我猜想可能是把减号没截全...

**Comment by Tangtonton** [comment]
[IMG]http://i68.tinypic.com/2l94569.png[/IMG]
这个识别成： 4+2 =2

[IMG]http://i67.tinypic.com/2d9qkav.png[/IMG]
这个识别成： 7+5 = 32

感觉你们不会啊。。你们都是Linux的？windows才会这样？？

**Comment by clouduan** [comment]
这个真的迷，_(:з」∠)_，我在 Linux 和 Windows 上都能正确识别的_(:з」∠)_
我也不知道哪里出问题了_(:з」∠)_

**Comment by Tangtonton** [comment]
明天才能调试了。。一天才两次挑战机会。。。。。。
我感觉不是分割的问题，是识别的问题。
难道是汉明距离不够准确？
我可以改成最短距离吗？我用大奶机玩的，应该速度应该够。。

**Comment by clouduan** [comment]
好，大佬可以自己改一下源码。
我是准备了两个小号，加上主号一共三个号，没机会了我就把三个号拉个群，然后就又可以玩了 :neckbeard: 

不过不建议搞了，如果不是为了兴趣的话（这个娃娃是骗人的，到现在客服都不回我消息 😅

**Comment by Tangtonton** [comment]
原来娃娃是骗人的😅。有空再研究下。。
谢谢你的回复

**Comment by Tangtonton** [comment]
我把错误识别的图保存下来，然后把错误识别的数字图片用源码的Hash算法算一下，把结果替换到 hash.json 里对应的数字，改完识别结果100%。😄😄😄

不过还是有一个出现分割错误：
http://i64.tinypic.com/2u5xi1d.png
识别成: 93 + 4 = 137
这个应该是纵向切割算法的问题。

**Comment by clouduan** [comment]
这个好强！两个4连在一起，按照目前的分割方法是没法分的 :neckbeard:

**Comment by clouduan** [comment]
@Tangtonton 娃娃不是骗人的 😅 ，我今天来个快递，拿到了。详见： https://zhuanlan.zhihu.com/p/36387916

加油哦~
