### ISSUE TITLE
这是什么问题呢

### ISSUE THREAD

**Issue by huaji1992** [clouduan/WechatGameAutoPlayer#16]
Could not find a version that satisfies the requirement pyHook (from PyUserInput==0.1.11->-r requirements.txt (line 3)) (from versions: )
No matching distribution found for pyHook (from PyUserInput==0.1.11->-r requirements.txt (line 3))

**Comment by clouduan** [comment]
https://github.com/clouduan/WechatGameAutoPlayer/issues/9 看这个
