### ISSUE TITLE
数字和符号识别错误，可以弄个自己训练图片的教程吗？谢谢

### ISSUE THREAD

**Issue by huaji1992** [clouduan/WechatGameAutoPlayer#17]

**Comment by clouduan** [comment]
嗯。这个基本不用训练的，因序列值已经提前生成了。
至于识别错误我觉得多半是区域没选好的原因，你也可以在程序中加些调试语句看看是什么原因。
以前的 issues 可具有参考意义。

**Comment by clouduan** [comment]
emmm首先你可以看下截图有没有截对（把cut之后的图`show()`一下），加号识别为减号一般是图没有截全。
当然如果问题不出在这里的话就要重新生成序列值了，但是这个比较麻烦，不建议弄（浪费时间）。
https://github.com/1033020837/WechatGameScript 这个项目你应该已经试过，已经加了自行训练的详细说明。
