### ISSUE TITLE
如何应对倒数几道题时间轴飞速消失的问题？

### ISSUE THREAD

**Issue by clouduan** [clouduan/WechatGameAutoPlayer#2]
这个游戏的有个极其可恶的设定：在答题数到37左右时，答题时间突然缩短，导致程序措手不及。详情见[用Python玩微信小游戏加减大师，从套路到被套路。。。
](https://www.bilibili.com/video/av22233811)

**Comment by clouduan** [comment]
目前唯一能做的就是提高程序的运行效率。可以采取的办法有但不限于以下：
- 优化代码，这个是必不可少的。
- 将 python 脚本编译为字节码运行，应该有一定作用

**Comment by clouduan** [comment]
需要分别测一下**截屏**和**识别**过程的耗时

**Comment by 1033020837** [comment]
你好，我也在写这个的脚本，目前也是卡在了最后几道题，程序反应不过来。我把每个阶段的耗时都测了一下，发现大部分时间都花在了截图以及读取截图的子进程的输出上，请问你有没有想出好的解决办法？

**Comment by clouduan** [comment]
@1033020837 目前还没有...因为截图花费的时间比较多而且似乎是硬伤没法优化。我还没来得及具体测量截图和识别过程的时间（这段时间在忙考试ing。
最后几题的速度实在是太快啦。。感觉 hold 不住啊。
如果还有一种思路，或许可以试试用 fiddler 抓包改数据 :rofl: ？

**Comment by clouduan** [comment]
@clouduan 测量了截屏和点击的耗时，令人震惊！
### 实验
利用 [TimingMeasurement.py](https://github.com/clouduan/WechatGameAutoPlayer/blob/master/TimingMeasurement.py) 测量的数据如下：
```python
# first time
get_screenshot:0.41169
click:0.00366
recognize:0.38148

# second time
get_screenshot:2.03459
click:0.00212
recognize:0.34673
```

### 结论：
点击和识别耗时稳定，分别在 0.03s 和 0.3s 左右，截图受所截屏幕内容影响很大，界面越绚丽越慢，越朴素越快。。。所以对于游戏界面，其耗时可想而知。所以终极办法就是用@1033020837 大佬的**投屏**方法了。

**Comment by 1033020837** [comment]
你的识别方法还可以改进一下，使用机器学习中的逻辑回归或者是简单的神经网络模型，都可以将识别时间降到0.1s以内的。

**Comment by clouduan** [comment]
论 `time.time()`, `time.clock()`,`time.perf_counter()`, `time.process_time()` 的区别..._(:з」∠)_
还有 `timeit`模块...

**Comment by clouduan** [comment]
## 前言
优化了运算，采用了投屏之后，终于成功拿到了娃娃，开心~
又测了一波数据：
``` python
GetScreenshot: 0.02556s
HorizontalCut: 0.00038s
VerticalCut: 0.00022s
VerticalCut: 0.00020s
Recognize: 0.02295s
One loop:  0.17238828365448366
```
可以看出一个循环用时0.2s不到，这还是在加了0.1s延迟的情况下，不加延迟的话一个循环才0.07s！其中优化一张图 hash 值运算的经历震撼很大，让我直观地感受了 numpy 的矩阵运算速度比 for 循环快了十万八千里！
## 疑问
话题又回到 adb 上面，按理来说投屏软件也是使用 adb 操作（或者不是？那是啥？），现在假设投屏软件也使用 adb 进行操作，为啥其速度几乎可以实时同步？难道是因为投到电脑上的界面变模糊降低了处理复杂程度？那这样的话我用 adb 应该也可以实现咯？但有一个很明显的现象可以判定并不是像素模糊导致处理速度变快，那就是模拟点击也比用 adb 快了许多（模拟点击不牵扯像素问题）。所以这一切还是很迷...
## 结语
希望哪天遇到高人指点吧...(:з」∠)

**Comment by clouduan** [comment]
v2ex 下的回答： https://www.v2ex.com/t/451708#reply27

**Comment by clouduan** [comment]
Solved.
