### ISSUE TITLE
OSerror:cannot identify image file'screenshot.png'

### ISSUE THREAD

**Issue by quinn1994** [clouduan/WechatGameAutoPlayer#27]

**Comment by clouduan** [comment]
能提供更多报错信息吗？

**Comment by quinn1994** [comment]
非常感谢版主百忙中的回复！
第一行报错是sh：1：adb:not:found
我感觉是没装adb模块，正在尝试安装。

**Comment by quinn1994** [comment]
我的系统ubuntu，另外还有两个问题。您在readme中说到，可用gimp测得坐标，该坐标指的是屏幕坐标吗？另外我有个困惑，如果您是用的投屏大法，还需要adb吗？

**Comment by clouduan** [comment]
@quinn1994 你一定是运行的 AutoPlay.py 
应该运行的是 AutoPlayPC.py 
投屏的话不需要adb。点击和截图都在电脑上完成。

你先把投屏放置好，然后截取电脑的全屏图片，再用 gimp 测量等式区域再屏幕中所处的位置（即坐标）

**Comment by quinn1994** [comment]
好的好的，感谢
