### ISSUE TITLE
为啥Vysor的图像很模糊，感觉看的不是很清楚，是不是要专业版啊

### ISSUE THREAD

**Issue by Yiutto** [clouduan/WechatGameAutoPlayer#28]

**Comment by clouduan** [comment]
我没用专业版还是挺清晰的…这样的话你找一个好点的投屏软件吧

**Comment by clouduan** [comment]
@Yiutto 因为每个人的手机屏幕参数不同，所以用我的手机生成的hash序列在别人的手机上面识别率并不高，你出现的那些识别错误就是这个原因所引起。
我有打算
- 用机器学习实现图片字符的识别
- 增加训练方法

不过这些要等我这周考完试才会弄（也说不定）。

**Comment by clouduan** [comment]
弃坑了...
