### ISSUE TITLE
请问这可以用在ios 还是安卓的呢

### ISSUE THREAD

**Issue by xiz327** [clouduan/WechatGameAutoPlayer#4]

**Comment by clouduan** [comment]
目前只适用于安卓，使用 adb (Android debug bright) 来操作截屏的。
你需要的话可以使用 iOS 的调试工具改一下。

**Comment by clouduan** [comment]
@xiz327 更新了一波，需要将手机投屏的，如果投屏那一步没问题的话就OK的 🙈 ，感兴趣可以试试。
