### ISSUE TITLE
Ubuntu16.04 and Windows OSError

### ISSUE THREAD

**Issue by hubert03** [clouduan/WechatGameAutoPlayer#5]
Traceback (most recent call last):
  File "AutoPlay.py", line 42, in <module>
    Play()
  File "AutoPlay.py", line 37, in Play
    judgement = Judge(screenshot)
  File "AutoPlay.py", line 22, in Judge
    expr = ocr.Recognize(image)
  File "/home/umete/WechatGameAutoPlayer/Recognize.py", line 12, in Recognize
    img = Image.open(imgFile).convert('L')
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f2c8f4f9fc0>

**Comment by clouduan** [comment]
@hubert03 It seems you didn't set up ADB on Ubuntu correctly :thinking:.  
Try typing `adb devices` in your terminal and see if your ADB can detect your phone. If your device isn't displayed, you have to set up ADB on your PC.

**Comment by hubert03** [comment]
Thank you so much and I'll try it later.

**Comment by hubert03** [comment]
![image](https://user-images.githubusercontent.com/24841291/39092491-896ce076-4641-11e8-87e6-543bde604336.png)
![image](https://user-images.githubusercontent.com/24841291/39092495-921f53d4-4641-11e8-8a68-e9bce5af34c9.png)

**Comment by clouduan** [comment]
Hmm, 首先这个程序目前只支持1080*1920屏幕分辨率的手机，因为我当时就是用我的匹配的。其它分辨率的需要改一行代码，这行代码所做的就是截取等式区域
https://github.com/clouduan/WechatGameAutoPlayer/blob/13bb3d7bb85b050cb7d44bd6dc7243efe4f7eb08/Recognize.py#L13
然后，确保是在游戏开始的界面，也就是包含数字的那个界面。

**Comment by clouduan** [comment]
#8

**Comment by clouduan** [comment]
#8
