### ISSUE TITLE
加减号识别出错？

### ISSUE THREAD

**Issue by myhomies** [clouduan/WechatGameAutoPlayer#6]
不知道是不是我程序问题还是？python2.7，屏幕分辨率1980X1080
刚升级到3.6也试了下，识别加减号出错

![23](https://user-images.githubusercontent.com/22335315/39103107-7e987fa8-46db-11e8-9b2b-27d6a32d3461.jpg)

![_20180423094749](https://user-images.githubusercontent.com/22335315/39103103-72351596-46db-11e8-9e5e-25f918c540cb.png)

**Comment by myhomies** [comment]
修改了这个参数出现卡的问题，然后没法继续，期待你的更新，加油

**Comment by clouduan** [comment]
@myhomies 已更新，基本上可以说适配了所有机型 🙈 ，感兴趣可以试试。
