### ISSUE TITLE
想问下我这情况是什么原因？

### ISSUE THREAD

**Issue by myhomies** [clouduan/WechatGameAutoPlayer#7]
一直显示类似这样的
GetScreenshot: 0.04727s
Error occurred:  list index out of range
是哪个依赖包的问题？

**Comment by clouduan** [comment]
嗯，貌似是分割图片那里遇到了问题，你把try except 两行删掉运行，再贴一下报错信息可以吗？（我当时为了方便用了try except，但是这样不太好排错...）

**Comment by myhomies** [comment]
有没有破解版的Vysor，设置清晰要钱啊

**Comment by clouduan** [comment]
这个我不清楚啊，或者你可以找一个替代的投屏软件？（不过那样折腾太浪费时间了。。不过你要找的话我可以推荐一个叫 Apowermirror，好像比这个清晰，但是界面比Vysor难看

**Comment by myhomies** [comment]
,try except 两行修改后运行报错,试了下Apowermirror，感觉可能是我电脑分辨率太低吧（1600X900），接着按照网上方法破解Vysor后，设置清晰度感觉更模糊，一运行就出现左键异常的情况，心累   我好绝望T_T

**Comment by clouduan** [comment]
emmm, 这样看来，这个也看人品了 😅

**Comment by zpjlove** [comment]
出现了同样地问题，Error occurred: list index out of range

**Comment by clouduan** [comment]
@zpjlove 我目前只在我自己的电脑上测过...看来稳定性还很脆弱...我刚刚重新改了一些，可以定位出错的位置，想知道哪里出错了 QAQ

**Comment by zpjlove** [comment]
img = Binaryzation(img)，得到的img是全为0的列表

**Comment by clouduan** [comment]
嗯，我觉得问题应该不在这里，二值化应该是没问题的。
你可以单独运行以下 ImgTools.py 试试，如果这个没问题，那就是在屏幕截图分割时出问题了。

**Comment by zpjlove** [comment]
单独运行没问题

**Comment by clouduan** [comment]
嗯，那就说明时在截屏+分割时出问题了，确认一下你有测量等式区域并且把坐标写在 Config.py 里面吗

**Comment by zpjlove** [comment]
location_on_pc = {
    'left_top_x': 100,
    'left_top_y': 400,
    'right_buttom_x': 600,
    'right_buttom_y': 750,
    'click_true_x': 180,
    'click_true_y': 1000,
    'click_false_x': 530,
    'click_false_y': 1000
}
这是我测量的等式区域

**Comment by Qing-King** [comment]
使用pymouse的时候，一直报错没有pymouse里面import的库没有安装，但是pyHook库一直无法安装

**Comment by clouduan** [comment]
@Qing-King 能发下具体出错信息么？pyhook在这里下载，然后用pip安装：https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook

**Comment by Qing-King** [comment]
@clouduan   ====== RESTART: C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlay.py ======
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlay.py", line 1, in <module>
    from Util import time_it
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\Util.py", line 1, in <module>
    from ImgTools import *
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\ImgTools.py", line 2, in <module>
    from TimeIt import time_it
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\TimeIt.py", line 16, in <module>
    from pymouse import PyMouse
  File "D:\python36\lib\site-packages\pymouse\__init__.py", line 92, in <module>
    from pymouse.windows import PyMouse, PyMouseEvent
  File "D:\python36\lib\site-packages\pymouse\windows.py", line 21, in <module>
    from win32api import GetSystemMetrics
ModuleNotFoundError: No module named 'win32api'

**Comment by clouduan** [comment]
需要装 pywin32，这个可以去网上搜一下

**Comment by Qing-King** [comment]
@clouduan   好的 谢谢  我安装一下

**Comment by clouduan** [comment]
#8

**Comment by clouduan** [comment]
#8
