### ISSUE TITLE
截图失败,cannot identify image file 'screenshot.png'

### ISSUE THREAD

**Issue by Qing-King** [clouduan/WechatGameAutoPlayer#8]
cmd窗口可以运行adb命令 
config也通过pyhook自带的example得到了坐标

运行AutoPlay.py得到这样的报错，显示找不到截得文件

====== RESTART: C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlay.py ======
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlay.py", line 32, in <module>
    Play()
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\TimeIt.py", line 7, in wrap
    result = func(*args)
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlay.py", line 18, in Play
    scr = get_screenshot()
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlay.py", line 9, in get_screenshot
    scr = Image.open('screenshot.png')
  File "D:\python36\lib\site-packages\PIL\Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'screenshot.png'

**Comment by clouduan** [comment]
emmm, 那个看说明要仔细啊 :joy: ，应该运行 AutoPlayPC.py，而不是AutoPlay.py，后者因为adb太慢了所以行不通的 :neckbeard:

**Comment by Qing-King** [comment]
@clouduan   再试了一下
Horizontal cut failed.
然后后面的就全部崩溃

get_screenshot: 0.11774s
Horizontal cut failed.
horizontal_cut: 0.00517s
Error occurred: 
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\AutoPlayPC.py", line 42, in Play
    expr = recognize(scr)
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\TimeIt.py", line 7, in wrap
    result = func(*args)
  File "C:\Users\admin\Desktop\WechatGameAutoPlayer\ImgTools.py", line 104, in recognize
    chars1 = vertical_cut(h_cut_imgs[0])
TypeError: 'NoneType' object is not subscriptable

**Comment by clouduan** [comment]
emmm 这个问题出现得确实很频繁，提示是水平分割出了问题。大概是截图有问题或者 config.py 里面参数设置不正确。具体你可以在代码中调一调，比如在某些地方加上 `img.show()` 看下获取到的截图到底如何，找到水平分割出错的原因。

**Comment by clouduan** [comment]
> 我先是通灌Vysor将你的screenshots里面的0th截电脑上面投影的图获得，保存进screenshots目录。

你在这里截的图是全图还是只截了等式区域？这里应该截全图，不妨把你截的图发上来看看？我试试

**Comment by Qing-King** [comment]
@clouduan GitHub上传图片太慢了，我通过邮件发给你了

**Comment by clouduan** [comment]
你可以参考下：我在 recognize.py 中加了这两行话，然后输出是这样：
```python
if __name__ == '__main__':
    """
    以下代码只用于debug
    """
    scr = Image.open('test.png')
    print(scr.size)
    scr = scr.crop([0, 750, 1080, 1150])
    print(recognize(scr))
```
然后输出是 (525, 942)，说明你这个图片的大小不是（1080，1920），所以后面的剪切部分也就是
```
scr = scr.crop([0, 750, 1080, 1150])
```
里面的数值并不适用。

**Comment by clouduan** [comment]
所以建议你在 AutoPlayPC.py 文件中加上这么一句：
```python
def Play():
    m = PyMouse()
    flag = ""
    while True:
        # start = time.perf_counter()
        time.sleep(0.1)
        try:
            scr = get_screenshot()
            scr.show()      # 加上这一句
            expr = recognize(scr)
```
这样每次就可以显示你所截图的等式区域到底是怎样的，看看是不是正常。

**Comment by clouduan** [comment]
嗯..我可能需要给你说说，之前说得有些模糊。大概是这样的：
AutoPlayPC.py 是主文件，它是根据 config.py 里面的数据直接截取等式区域，而不是整个手机屏幕，所以这里肯定不是1080x1920 的。
ImgTools.py 里面的`if __name__ == '__main__':` 以及后面的部分是recognize函数的单独测试语句，它需要的是打开整个图片，不过这个可以不用管。

现在，你只需要在 AutoPlayPC.py 文件里面加入这句：
```python
def Play():
    m = PyMouse()
    flag = ""
    while True:
        # start = time.perf_counter()
        time.sleep(0.1)
        try:
            scr = get_screenshot()
            scr.show()      # 加上这一句
            expr = recognize(scr)
```
而不是你所加的这句 ` print('scr.size      '+str(scr.size))    #更改处` 。

然后看看显示截取的等式区域是不是正确。

**Comment by clouduan** [comment]
你这个config文件里的参数其实也是明显不正确的，因为等式区域很明显不是 1080x1920

**Comment by Qing-King** [comment]
我更改了config 并且加入了scr.show()
得到的图片通过，图片已经可以截取题目，报错还是Horizontal cut failed.
![tim 20180506000540](https://user-images.githubusercontent.com/34064541/39665133-cade6c84-50c1-11e8-9c42-ea2369efa9a7.png)

**Comment by clouduan** [comment]
没道理啊 :neck beard: 可以把 show的图片发给我吗？（我觉得最好的办法是你读一下源码了:disappointed_relieved:

**Comment by clouduan** [comment]
嗯不对，你这 show() 的图按理说应该是只包含等式区域才对，参考下图![](https://i.imgur.com/UPVe2bG.png)

**Comment by clouduan** [comment]
我在readme 里面写了如何获取等式区域坐标的方法，你应该仔细看看:disappointed_relieved:

**Comment by Qing-King** [comment]
@clouduan   多谢你了，运行结果已经可以
```
get_screenshot: 0.06322s
horizontal_cut: 0.00528s
vertical_cut: 0.00332s
vertical_cut: 0.00391s
recognize: 2.82737s
4-2==1 False

```
```

if flag == expr:
                continue
            else:
                flag = expr
                if eval(expr):
                    m.click(loc['click_true_x'], loc['click_true_y'], 1)
                else:
                    m.click(loc['click_false_x'], loc['click_false_y'], 1)
        except:
            if 'scr' in vars():
                scr.save('failed.png')
            print('Error occurred: ')
            print(traceback.print_exc())
```
运行这一段代码的时候，直接
```
if flag == expr:
                continue
```
结束循环了 
明天细读代码吧
谢谢
