### ISSUE TITLE
ModuleNotFoundError: No module named 'windows'

### ISSUE THREAD

**Issue by xing0036** [clouduan/WechatGameAutoPlayer#9]
为什么我运行的时候显示这个问题，找不到解决办法ModuleNotFoundError: No module named 'windows'

**Comment by clouduan** [comment]
把详细报错信息发来

**Comment by bwinzhb** [comment]
zhou@_ MINGW64 ~/Desktop/WechatGameAutoPlayer-master
$ pip3 install -r requirements.txt
Ignoring python3-xlib: markers 'sys_platform == "linux"' don't match your environment
Collecting pywin32==223 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9f/9d/f4b2170e8ff5d825cd4398856fee88f6c70c60bce0aa8411ed17c1e1b21f/pywin32-223-cp36-cp36m-win_amd64.whl
Collecting PyUserInput==0.1.11 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/d0/09/17fe0b16c7eeb52d6c14e904596ddde82503aeee268330120b595bf22d7b/PyUserInput-0.1.11.tar.gz
Collecting numpy==1.14.2 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/30/70/cd94a1655d082b8f024b21af1eb13dd0f3035ffe78ff43d4ff9bb97baa5f/numpy-1.14.2-cp36-none-win_amd64.whl
Collecting Pillow==5.1.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/a4/86/283719dac6309cf483452abb09759be9b2c0974435ed608dc67949127e13/Pillow-5.1.0-cp36-cp36m-win_amd64.whl
Collecting pyscreenshot==0.4.2 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/49/c3/bccc64677e87c7a14a953ba15e987a6e8c5baa354f8ffe932335a82a0438/pyscreenshot-0.4.2.tar.gz
Collecting pyHook (from PyUserInput==0.1.11->-r requirements.txt (line 3))
  Could not find a version that satisfies the requirement pyHook (from PyUserInput==0.1.11->-r requirements.txt (line 3)) (from versions: )
No matching distribution found for pyHook (from PyUserInput==0.1.11->-r requirements.txt (line 3))

zhou@_ MINGW64 ~/Desktop/WechatGameAutoPlayer-master
$ python AutoPlayPC.py
Traceback (most recent call last):
  File "AutoPlayPC.py", line 2, in <module>
    from pymouse import PyMouse
ModuleNotFoundError: No module named 'pymouse'

**Comment by clouduan** [comment]
@xing0036 找到python安装路径下 Lib\site-packages\pymouse\__init__.py 这个文件，把下面一句
```python
from windows import PyMouse, PyMouseEvent
```
改为
```python
from pymouse.windows import PyMouse, PyMouseEvent
```
即可

**Comment by clouduan** [comment]
@bwinzhb 
```
pip install pymouse
```

**Comment by xing0036** [comment]
`File "<ipython-input-2-50cad2e26aa2>", line 1, in <module>
    runfile('F:/浏览器下载/chorm浏览器/pyhton/WechatGameAutoPlayer-master/WechatGameAutoPlayer-master/AutoPlayPC.py', wdir='F:/浏览器下载/chorm浏览器/pyhton/WechatGameAutoPlayer-master/WechatGameAutoPlayer-master')

  File "F:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "F:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/浏览器下载/chorm浏览器/pyhton/WechatGameAutoPlayer-master/WechatGameAutoPlayer-master/AutoPlayPC.py", line 2, in <module>
    from pymouse import PyMouse

  File "F:\Anaconda\lib\site-packages\pymouse\__init__.py", line 92, in <module>
    from pymouse.windows import PyMouse, PyMouseEvent

  File "F:\Anaconda\lib\site-packages\pymouse\windows.py", line 23, in <module>
    import pythoncom, pyHook

ModuleNotFoundError: No module named 'pyHook'`

`Collecting pyhook
  Could not find a version that satisfies the requirement pyhook (from versions: )
No matching distribution found for pyhook`

现在我这个是这个PyHook库没有，我试着用pip还有Conda安装都没有成功，这个是因为什么

**Comment by clouduan** [comment]
@xing0036 pyhook 在这里下载，然后用 pip 手动安装

**Comment by xing0036** [comment]
楼主，这个pyhook的下载链接你没发出来吧

**Comment by clouduan** [comment]
@xing0036 pyhook 在这里下载，然后用 pip 手动安装
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook

刚忘了发了，抱歉...

**Comment by xing0036** [comment]
没事没事，我下午在那找没找到，刚才突然就又看到了

**Comment by sewevi** [comment]
@clouduan 我用pip安装了win32api还是报错要怎么解决？
Traceback (most recent call last):
  File "F:/Language/Pycharm/PyCharm 2018.1.2/WechatGameAutoPlayer-master/AutoPlayPC.py", line 2, in <module>
    from pymouse import PyMouse
  File "F:\Language\Pycharm\PyCharm 2018.1.2\venv\lib\site-packages\pymouse\__init__.py", line 92, in <module>
    from pymouse.windows import PyMouse, PyMouseEvent
  File "F:\Language\Pycharm\PyCharm 2018.1.2\venv\lib\site-packages\pymouse\windows.py", line 21, in <module>
    from win32api import GetSystemMetrics
ModuleNotFoundError: No module named 'win32api'

**Comment by fanghaotianHT** [comment]
C:\Users\lenovo\Anaconda3\python.exe C:/Users/lenovo/PycharmProjects/untitled4/AutoPlayPc.py
Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/untitled4/AutoPlayPc.py", line 3, in <module>
    from ImgTools import recognize
ModuleNotFoundError: No module named 'ImgTools'

Process finished with exit code 1
为什么我安装了Imgtools还是报错

**Comment by clouduan** [comment]
@sewevi @fanghaotianHT 
看这个新的 issue https://github.com/clouduan/WechatGameAutoPlayer/issues/22
已关闭的issue下请不要回复了，会打扰到其他人的。

**Comment by duxuegang** [comment]
已经找不到了 pyhook

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
